### PR TITLE
[WM-1629] Add AppSec Trivy action

### PR DESCRIPTION
**Pull request by dinvlad**
https://broadworkbench.atlassian.net/browse/WM-1629

### CODE REVIEW

**Review by salonishah11 — APPROVED** [review]

**Review by mspector — APPROVED** [review]

**Comment by salonishah11** [comment]
Thank you for adding this @dinvlad!

**Comment by cjllanwarne** [comment]
Isn't this covered by using an approved base image?

**Comment by dinvlad** [comment]
I think these are separate. The action is used to verify that you image is using the base image, or if it's not then the action will scan it. Unfortunately, we need to have this for compliance, to show that we monitor all images.

**Comment by cjllanwarne** [comment]
@dinvlad sounds good. Feel free to go ahead and merge these two PRs at your convenience

**Pull request merged**
